HAI 1.3
	VISIBLE SUM OF 0 AN BOTH OF WIN AN BOTH OF WIN AN WIN
	VISIBLE SUM OF 0 AN BOTH OF WIN AN BOTH OF WIN AN FAIL
	VISIBLE SUM OF 0 AN BOTH OF FAIL AN BOTH OF WIN AN WIN
	VISIBLE SUM OF 0 AN BOTH OF FAIL AN BOTH OF WIN AN FAIL
KTHXBYE
