HAI 1.3
	I HAS A var1 ITZ "0"
	I HAS A var2 ITZ "1.234"
	VISIBLE SUM OF 0 AN DIFFRINT var1 var2
	VISIBLE SUM OF 0 AN DIFFRINT var1 FAIL
	VISIBLE SUM OF 0 AN DIFFRINT FAIL var2
	VISIBLE SUM OF 0 AN DIFFRINT var1 WIN
	VISIBLE SUM OF 0 AN DIFFRINT WIN var2
	VISIBLE SUM OF 0 AN DIFFRINT var1 0
	VISIBLE SUM OF 0 AN DIFFRINT 0 var2
	VISIBLE SUM OF 0 AN DIFFRINT var1 1
	VISIBLE SUM OF 0 AN DIFFRINT 1 var2
	VISIBLE SUM OF 0 AN DIFFRINT var1 0.0
	VISIBLE SUM OF 0 AN DIFFRINT 0.0 var2
	VISIBLE SUM OF 0 AN DIFFRINT var1 1.234
	VISIBLE SUM OF 0 AN DIFFRINT 1.234 var2
	VISIBLE SUM OF 0 AN DIFFRINT var1 "0"
	VISIBLE SUM OF 0 AN DIFFRINT "0" var2
	VISIBLE SUM OF 0 AN DIFFRINT var1 "1"
	VISIBLE SUM OF 0 AN DIFFRINT "1" var2
	VISIBLE SUM OF 0 AN DIFFRINT var1 "0.0"
	VISIBLE SUM OF 0 AN DIFFRINT "0.0" var2
	VISIBLE SUM OF 0 AN DIFFRINT var1 "1.234"
	VISIBLE SUM OF 0 AN DIFFRINT "1.234" var2
KTHXBYE
