HAI 1.2
	VISIBLE SUM OF 0 AN ANY OF FAIL AN ANY OF FAIL AN FAIL AN WIN MKAY AN WIN MKAY
	VISIBLE SUM OF 0 AN ANY OF FAIL AN ANY OF FAIL AN FAIL AN FAIL MKAY AN WIN MKAY
	VISIBLE SUM OF 0 AN ANY OF FAIL AN ANY OF FAIL AN FAIL AN WIN MKAY AN FAIL MKAY
	VISIBLE SUM OF 0 AN ANY OF FAIL AN ANY OF FAIL AN FAIL AN FAIL MKAY AN FAIL MKAY
KTHXBYE
