HAI 1.4
    CAN HAS STDLIB?
    I HAS A val1 ITZ I IZ STDLIB'Z BLOW YR 10 MKAY
    I HAS A val2 ITZ I IZ STDLIB'Z BLOW YR 10 MKAY
    I HAS A val3 ITZ I IZ STDLIB'Z BLOW YR 10 MKAY
    VISIBLE val1
    VISIBLE val2
    VISIBLE val3
KTHXBYE
