HAI 1.3
	I HAS A var1
	I HAS A var2 ITZ ""
	I HAS A var3 ITZ 0
	I HAS A var4 ITZ 0.00
	I HAS A var5 ITZ "Lorem ipsum dolor sit"
	I HAS A var6 ITZ 1
	I HAS A var7 ITZ 2.345
	VISIBLE SUM OF 0 AN NOT var1
	VISIBLE SUM OF 0 AN NOT var2
	VISIBLE SUM OF 0 AN NOT var3
	VISIBLE SUM OF 0 AN NOT var4
	VISIBLE SUM OF 0 AN NOT var5
	VISIBLE SUM OF 0 AN NOT var6
	VISIBLE SUM OF 0 AN NOT var7
KTHXBYE
