HAI 1.3
	I HAS A var1
	I HAS A var2
	VISIBLE SUM OF 0 AN BOTH SAEM var1 AN var2
	VISIBLE SUM OF 0 AN BOTH SAEM var1 AN FAIL
	VISIBLE SUM OF 0 AN BOTH SAEM FAIL AN var2
	VISIBLE SUM OF 0 AN BOTH SAEM var1 AN WIN
	VISIBLE SUM OF 0 AN BOTH SAEM WIN AN var2
	VISIBLE SUM OF 0 AN BOTH SAEM var1 AN 0
	VISIBLE SUM OF 0 AN BOTH SAEM 0 AN var2
	VISIBLE SUM OF 0 AN BOTH SAEM var1 AN 1
	VISIBLE SUM OF 0 AN BOTH SAEM 1 AN var2
	VISIBLE SUM OF 0 AN BOTH SAEM var1 AN 0.0
	VISIBLE SUM OF 0 AN BOTH SAEM 0.0 AN var2
	VISIBLE SUM OF 0 AN BOTH SAEM var1 AN 1.234
	VISIBLE SUM OF 0 AN BOTH SAEM 1.234 AN var2
	VISIBLE SUM OF 0 AN BOTH SAEM var1 AN "0"
	VISIBLE SUM OF 0 AN BOTH SAEM "0" AN var2
	VISIBLE SUM OF 0 AN BOTH SAEM var1 AN "1"
	VISIBLE SUM OF 0 AN BOTH SAEM "1" AN var2
	VISIBLE SUM OF 0 AN BOTH SAEM var1 AN "0.0"
	VISIBLE SUM OF 0 AN BOTH SAEM "0.0" AN var2
	VISIBLE SUM OF 0 AN BOTH SAEM var1 AN "1.234"
	VISIBLE SUM OF 0 AN BOTH SAEM "1.234" AN var2
KTHXBYE
