HAI 1.3
	VISIBLE SUM OF 0 AN ALL OF WIN AN ALL OF WIN AN WIN AN WIN MKAY AN WIN MKAY
	VISIBLE SUM OF 0 AN ALL OF WIN AN ALL OF WIN AN WIN AN FAIL MKAY AN WIN MKAY
	VISIBLE SUM OF 0 AN ALL OF WIN AN ALL OF WIN AN WIN AN WIN MKAY AN FAIL MKAY
	VISIBLE SUM OF 0 AN ALL OF WIN AN ALL OF WIN AN WIN AN FAIL MKAY AN FAIL MKAY
KTHXBYE
