HAI 1.3
	I HAS A var1 ITZ "0"
	I HAS A var2 ITZ "1.234"
	VISIBLE SUM OF 0 AN BOTH SAEM var1 var2
	VISIBLE SUM OF 0 AN BOTH SAEM var1 FAIL
	VISIBLE SUM OF 0 AN BOTH SAEM FAIL var2
	VISIBLE SUM OF 0 AN BOTH SAEM var1 WIN
	VISIBLE SUM OF 0 AN BOTH SAEM WIN var2
	VISIBLE SUM OF 0 AN BOTH SAEM var1 0
	VISIBLE SUM OF 0 AN BOTH SAEM 0 var2
	VISIBLE SUM OF 0 AN BOTH SAEM var1 1
	VISIBLE SUM OF 0 AN BOTH SAEM 1 var2
	VISIBLE SUM OF 0 AN BOTH SAEM var1 0.0
	VISIBLE SUM OF 0 AN BOTH SAEM 0.0 var2
	VISIBLE SUM OF 0 AN BOTH SAEM var1 1.234
	VISIBLE SUM OF 0 AN BOTH SAEM 1.234 var2
	VISIBLE SUM OF 0 AN BOTH SAEM var1 "0"
	VISIBLE SUM OF 0 AN BOTH SAEM "0" var2
	VISIBLE SUM OF 0 AN BOTH SAEM var1 "1"
	VISIBLE SUM OF 0 AN BOTH SAEM "1" var2
	VISIBLE SUM OF 0 AN BOTH SAEM var1 "0.0"
	VISIBLE SUM OF 0 AN BOTH SAEM "0.0" var2
	VISIBLE SUM OF 0 AN BOTH SAEM var1 "1.234"
	VISIBLE SUM OF 0 AN BOTH SAEM "1.234" var2
KTHXBYE
