HAI 1.3
	VISIBLE SUM OF 0 AN WON OF WIN AN WON OF FAIL AN FAIL
	VISIBLE SUM OF 0 AN WON OF WIN AN WON OF WIN AN WIN
	VISIBLE SUM OF 0 AN WON OF FAIL AN WON OF FAIL AN FAIL
	VISIBLE SUM OF 0 AN WON OF FAIL AN WON OF WIN AN WIN
KTHXBYE
