HAI 1.3
	VISIBLE SUM OF 0 AN EITHER OF WIN AN EITHER OF FAIL AN FAIL
	VISIBLE SUM OF 0 AN EITHER OF WIN AN EITHER OF FAIL AN WIN
	VISIBLE SUM OF 0 AN EITHER OF FAIL AN EITHER OF FAIL AN FAIL
	VISIBLE SUM OF 0 AN EITHER OF FAIL AN EITHER OF FAIL AN WIN
KTHXBYE
