HAI 1.3
	I HAS A var1 ITZ A NOOB
	I HAS A var2 ITZ A TROOF
	I HAS A var3 ITZ A NUMBR
	I HAS A var4 ITZ A NUMBAR
	I HAS A var5 ITZ A YARN
	VISIBLE SUM OF 0 AN NOT var1
	VISIBLE SUM OF 0 AN var2
	VISIBLE var3
	VISIBLE var4
	VISIBLE var5
KTHXBYE
