HAI 1.3
	VISIBLE SUM OF 0 AN ANY OF FAIL AN FAIL AN FAIL AN FAIL MKAY
	VISIBLE SUM OF 0 AN ANY OF FAIL AN FAIL AN FAIL AN WIN MKAY
	VISIBLE SUM OF 0 AN ANY OF FAIL AN FAIL AN WIN AN FAIL MKAY
	VISIBLE SUM OF 0 AN ANY OF FAIL AN FAIL AN WIN AN WIN MKAY
	VISIBLE SUM OF 0 AN ANY OF FAIL AN WIN AN FAIL AN FAIL MKAY
	VISIBLE SUM OF 0 AN ANY OF FAIL AN WIN AN FAIL AN WIN MKAY
	VISIBLE SUM OF 0 AN ANY OF FAIL AN WIN AN WIN AN FAIL MKAY
	VISIBLE SUM OF 0 AN ANY OF FAIL AN WIN AN WIN AN WIN MKAY
	VISIBLE SUM OF 0 AN ANY OF WIN AN FAIL AN FAIL AN FAIL MKAY
	VISIBLE SUM OF 0 AN ANY OF WIN AN FAIL AN FAIL AN WIN MKAY
	VISIBLE SUM OF 0 AN ANY OF WIN AN FAIL AN WIN AN FAIL MKAY
	VISIBLE SUM OF 0 AN ANY OF WIN AN FAIL AN WIN AN WIN MKAY
	VISIBLE SUM OF 0 AN ANY OF WIN AN WIN AN FAIL AN FAIL MKAY
	VISIBLE SUM OF 0 AN ANY OF WIN AN WIN AN FAIL AN WIN MKAY
	VISIBLE SUM OF 0 AN ANY OF WIN AN WIN AN WIN AN FAIL MKAY
	VISIBLE SUM OF 0 AN ANY OF WIN AN WIN AN WIN AN WIN MKAY
KTHXBYE
