INCLUDE(ParseArguments)


FUNCTION(ADD_LOL_TEST TEST_NAME)
  PARSE_ARGUMENTS(ARG "LOLCODE;OUTPUT;ERROR" "" ${ARGN})

  IF(NOT ARG_LOLCODE)
    SET(ARG_LOLCODE ${CMAKE_CURRENT_SOURCE_DIR}/test.lol)
  ENDIF(NOT ARG_LOLCODE)

  SET( TEST_COMMAND python ${CMAKE_SOURCE_DIR}/test/testDriver.py ${CMAKE_BINARY_DIR}/lci ${ARG_LOLCODE} )

  IF(ARG_OUTPUT)
    LIST(APPEND TEST_COMMAND -o=${CMAKE_CURRENT_SOURCE_DIR}/${ARG_OUTPUT})
  ENDIF(ARG_OUTPUT)

  IF(ARG_ERROR)
    LIST(APPEND TEST_COMMAND -e=${CMAKE_CURRENT_SOURCE_DIR}/${ARG_ERROR})
  ENDIF(ARG_ERROR)


  ADD_TEST(NAME ${TEST_NAME} COMMAND ${TEST_COMMAND})

ENDFUNCTION()

