HAI 1.3
	VISIBLE SUM OF 0 AN ALL OF FAIL FAIL FAIL FAIL MKAY
	VISIBLE SUM OF 0 AN ALL OF FAIL FAIL FAIL WIN MKAY
	VISIBLE SUM OF 0 AN ALL OF FAIL FAIL WIN FAIL MKAY
	VISIBLE SUM OF 0 AN ALL OF FAIL FAIL WIN WIN MKAY
	VISIBLE SUM OF 0 AN ALL OF FAIL WIN FAIL FAIL MKAY
	VISIBLE SUM OF 0 AN ALL OF FAIL WIN FAIL WIN MKAY
	VISIBLE SUM OF 0 AN ALL OF FAIL WIN WIN FAIL MKAY
	VISIBLE SUM OF 0 AN ALL OF FAIL WIN WIN WIN MKAY
	VISIBLE SUM OF 0 AN ALL OF WIN FAIL FAIL FAIL MKAY
	VISIBLE SUM OF 0 AN ALL OF WIN FAIL FAIL WIN MKAY
	VISIBLE SUM OF 0 AN ALL OF WIN FAIL WIN FAIL MKAY
	VISIBLE SUM OF 0 AN ALL OF WIN FAIL WIN WIN MKAY
	VISIBLE SUM OF 0 AN ALL OF WIN WIN FAIL FAIL MKAY
	VISIBLE SUM OF 0 AN ALL OF WIN WIN FAIL WIN MKAY
	VISIBLE SUM OF 0 AN ALL OF WIN WIN WIN FAIL MKAY
	VISIBLE SUM OF 0 AN ALL OF WIN WIN WIN WIN MKAY
KTHXBYE
