HAI 1.3
	I HAS A var1
	I HAS A var2 ITZ WIN
	I HAS A var3 ITZ 1
	I HAS A var4 ITZ 2.345
	I HAS A var5 ITZ "Lorem ipsum dolor sit."
	SRS "var1" R NOOB
	SRS "var2" R NOOB
	SRS "var3" R NOOB
	SRS "var4" R NOOB
	SRS "var5" R NOOB
	VISIBLE SUM OF 0 AN NOT var1
	VISIBLE SUM OF 0 AN NOT var2
	VISIBLE SUM OF 0 AN NOT var3
	VISIBLE SUM OF 0 AN NOT var4
	VISIBLE SUM OF 0 AN NOT var5
KTHXBYE
